version: "3.7"

services:
  livuar_back:
    build: ./
    command: python livuar/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  livuar_db:
    image: postgres:12
    volumes:
      - livuar_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  livuar_postgres_data: