# Generated by Django 4.0.4 on 2022-05-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='big_photo',
            field=models.ImageField(upload_to='category/big/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='small_photo',
            field=models.ImageField(upload_to='category/small/'),
        ),
    ]
