# Generated by Django 4.0.4 on 2022-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='news/')),
                ('photo2', models.ImageField(upload_to='news/')),
                ('photo3', models.ImageField(upload_to='news/')),
                ('photo4', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
