# Generated by Django 4.0.4 on 2022-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_photo',
            field=models.ImageField(default='132.jpg', upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
